= Storage with RHOSP UPI
Antonio C. <sp38af (at) trikorasolutions (dot) com>
:revdate: {docdate}
:icons: font
:toc: left
:toclevels: 3
:toc-title: Table of Contents
:description: Deploy storage on RHOSP UPI

== Introduction

[.lead]
This section describes storage deployment options on RHOSP UPI.

== kubernetes/cloud-provider-openstack

=== Cinder

[.lead]
RHOSP Cinder

[source,bash]
----
ansible-playbook ocp/upi/upi_rhosp/ansible/50-ocp-storage-cinder-deploy.yaml \
  -i _local_config/ansible/inventory.yaml \
  -e @_local_config/network.yaml \
  -e @_local_config/${OCP_CLUSTER_NAME}/${OCP_CLUSTER_NAME}.yaml \
  -e @ocp/upi/ansible/defaults/main.yaml \
  -e @ocp/4.16/ansible/defaults/main.yaml \
  -e @ocp/upi/upi_rhosp/ansible/defaults/main.yaml
----

To test the configuration execute the following configuration that will deploy 
 an nginx pod with a volume attached to a PVC. The PVC should provision a PV
 automatically.

[source,bash]
----
oc apply -f ocp/upi/upi_rhosp/ansible/templates/kubernetes-cloud-provider-openstack-cinder-test.yaml
----

Check if the pod is up and running.

[source,bash]
----
oc get pod
----

Should show something like this.

[source,]
----
NAME    READY   STATUS    RESTARTS   AGE
nginx   1/1     Running   0          33s
----

Check the PV.

[source,bash]
----
oc get pv
----

[source,]
----
NAME         CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                          STORAGECLASS          REASON   AGE
pvc-xxxxxx   1Gi        RWO            Delete           Bound    default/csi-pvc-cinderplugin   csi-sc-cinderplugin            16h
----

Check the PVC.

[source,bash]
----
oc get pvc
----

[source,]
----
NAME                  STATUS   VOLUME    CAPACITY   ACCESS MODES   STORAGECLASS          AGE
csi-pvc-cinderplugin  Bound    pvc-xxx   1Gi        RWO            csi-sc-cinderplugin   19h
----

Check if the volume was created.

[source,bash]
----
openstack volume list
----

[source,]
====
+------------+------------+----------+------+-------------+
| ID         | Name       | Status   | Size | Attached to |
+------------+------------+----------+------+-------------+
| xxx-xxx... | pvc-xxxxxx | reserved |    1 |             |
+------------+------------+----------+------+-------------+
====

Delete the test resources.

[source,bash]
----
oc delete -f ocp/upi/upi_rhosp/ansible/templates/kubernetes-cloud-provider-openstack-cinder-test.yaml
----


=== Manila

[.lead]
RHOSP Manila

==== Deploy Manila

[source,bash]
----
ansible-playbook ocp/upi/upi_rhosp/ansible/50-ocp-storage-manila.yaml \
  -i _local_config/ansible/inventory.yaml \
  -e @_local_config/network.yaml \
  -e @_local_config/${OCP_CLUSTER_NAME}/${OCP_CLUSTER_NAME}.yaml \
  -e @ocp/upi/ansible/defaults/main.yaml \
  -e @ocp/4.16/ansible/defaults/main.yaml \
  -e @ocp/upi/upi_rhosp/ansible/defaults/main.yaml \
  -e @ocp/upi/upi_rhosp/ansible/defaults/ovhcloud.yaml
----

To test the configuration execute the following configuration that will deploy 
 an nginx pod with a volume attached to a PVC. The PVC should provision a PV
 automatically.

[source,bash]
----
oc apply -f ocp/4.15/upi_rhosp/ansible/files/kubernetes-cloud-provider-openstack-manila-test.yaml
----

Delete manila test.

[source,bash]
----
oc delete -f ocp/4.15/upi_rhosp/ansible/files/kubernetes-cloud-provider-openstack-manila-test.yaml
----

==== Undeploy Manila

Delete manila configuration.

[source,bash]
----
ansible-playbook ocp/upi/upi_rhosp/ansible/95-ocp-storage-manila-cleanup.yaml \
  -i _local_config/ansible/inventory.yaml \
  -e @_local_config/network.yaml \
  -e @_local_config/${OCP_CLUSTER_NAME}/${OCP_CLUSTER_NAME}.yaml \
  -e @ocp/upi/ansible/defaults/main.yaml \
  -e @ocp/4.16/ansible/defaults/main.yaml \
  -e @ocp/upi/upi_rhosp/ansible/defaults/main.yaml \
  -e @ocp/upi/upi_rhosp/ansible/defaults/ovhcloud.yaml
----

References: 

* https://github.com/kubernetes/cloud-provider-openstack
* Cinder: https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/cinder-csi-plugin/using-cinder-csi-plugin.md
* Manila: https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/manila-csi-plugin/using-manila-csi-plugin.md

==== openshift

* Manila: https://github.com/openshift/csi-driver-manila-operator
* Cinder: https://github.com/openshift/openstack-cinder-csi-driver-operator
* https://github.com/openshift/csi-operator/


*Cluster Storage Operator*

* https://docs.redhat.com/en/documentation/openshift_container_platform/4.15/html/operators/cluster-operators-ref#cluster-storage-operator_cluster-operators-ref
* https://github.com/openshift/cluster-storage-operator/tree/release-4.15

== Maintenance

*Stop node*

[source,bash]
----
ansible-playbook ocp/4.15/upi_rhosp/ansible/node-stop.yaml \
  -e nodename=node-name \
  -e rhosp_instance_name=rhosp-instance
----

*Start node*

[source,bash]
----
ansible-playbook ocp/4.15/upi_rhosp/ansible/node-start.yaml \
  -e nodename=node-name \
  -e rhosp_instance_name=rhosp-instance
----

*Restart node*

[source,bash]
----
ansible-playbook ocp/4.15/upi_rhosp/ansible/node-restart.yaml \
  -e nodename=node-name \
  -e rhosp_instance_name=rhosp-instance
----

== References

* https://docs.redhat.com/en/documentation/openshift_container_platform/4.11/html/installing/installing-on-openstack
* https://docs.redhat.com/en/documentation/openshift_container_platform/4.11/html/installing/installing-on-openstack#cluster-entitlements_installing-openstack-user
* https://github.com/openshift/installer/tree/release-4.15/upi/openstack
* https://docs.fedoraproject.org/en-US/fedora-coreos/provisioning-openstack/
* https://github.com/openshift/installer/blob/main/docs/user/openstack/install_upi.md
