---
- name: "Collect information"
  import_playbook: _common_rhosp.yaml
  when: ocp_cluster_id_tag is not defined

- name: "Setup OpenStack Load Balancer"
  hosts: "localhost"
  gather_facts: true

  tasks:

  - name: "Fetch FIP information"
    include_tasks: tasks/rhosp-fetch-fip-info.yaml

  - name: "Public LB Floating IP"
    ansible.builtin.debug:
      var: openstack_fip_api_address

  - name: "Create public API Load Balancer"
    openstack.cloud.loadbalancer:
      api_timeout: 120
      name: "{{ rhosp_loadbalancer_prefix }}-api-public"
      vip_network: "{{ rhosp_network }}"
      # floating_ip_address: "{{ openstack_fip_api_address }}"
      # delete_floating_ip: true
      state: present
    register: rhosp_lb_public_deploy_res

  - name: "Print Public LB Deploy output"
    ansible.builtin.debug:
      var: rhosp_lb_public_deploy_res

  - name: "Associate the Floating IP with the Public API LB"
    ansible.builtin.shell: |
      # openstack floating ip set --port <load_balancer_vip_port_id> <floating_ip_id>
      openstack floating ip set --port {{ rhosp_lb_public_deploy_res.load_balancer.vip_port_id }} {{ openstack_fip_api_id }}
    register: rhosp_lb_deploy_assoc_fp_public_res

  - name: "Print output of: Associate the Floating IP with the public API LB"
    ansible.builtin.debug:
      var: rhosp_lb_deploy_assoc_fp_public_res

  - name: "Create Internal API Load Balancer"
    openstack.cloud.loadbalancer:
      # assign_floating_ip: false
      name: "{{ rhosp_loadbalancer_prefix }}-api-internal"
      vip_network: "{{ rhosp_network }}"
      state: present
    register: rhosp_lb_internal_deploy_res

  - name: "Print Internal LB Deploy output"
    ansible.builtin.debug:
      var: rhosp_lb_internal_deploy_res

  - name: "Create APP Load Balancer"
    openstack.cloud.loadbalancer:
      api_timeout: 120
      name: "{{ rhosp_loadbalancer_prefix }}-app"
      vip_network: "{{ rhosp_network }}"
      # floating_ip_address: "{{ openstack_fip_api_address }}"
      # delete_floating_ip: true
      state: present
    register: rhosp_lb_app_deploy_res

  - name: "Print APP LB Deploy output"
    ansible.builtin.debug:
      var: rhosp_lb_app_deploy_res

  - name: "Associate the Floating IP with the APP LB"
    ansible.builtin.shell: |
      # openstack floating ip set --port <load_balancer_vip_port_id> <floating_ip_id>
      openstack floating ip set --port {{ rhosp_lb_app_deploy_res.load_balancer.vip_port_id }} {{ openstack_fip_apps_id }}
    register: rhosp_lb_deploy_assoc_fp_app_res

  - name: "Print output of: Associate the Floating IP with APP LB"
    ansible.builtin.debug:
      var: rhosp_lb_deploy_assoc_fp_app_res

  - name: "Create public API load-balancer pools"
    openstack.cloud.lb_pool:
      name: "{{ item.name }}"
      lb_algorithm: "ROUND_ROBIN"
      loadbalancer: "{{ rhosp_loadbalancer_prefix }}-api-public"
      protocol: "{{ item.protocol }}"
      state: present
    loop: "{{ rhosp_lb_public_ports }}"
    failed_when: false # there is no way of knowing if the pool already exists and it fails when creating again
    register: public_lb_pool_create_res

  - name: "Print output"
    ansible.builtin.debug:
      var: public_lb_pool_create_res

  - name: "Create public API load-balancer listeners"
    openstack.cloud.lb_listener:
      name: "{{ item.name }}"
      load_balancer: "{{ rhosp_loadbalancer_prefix }}-api-public"
      protocol: "{{ item.protocol }}"
      protocol_port: "{{ item.port }}"
      state: present
    loop: "{{ rhosp_lb_public_ports }}"

  - name: "Create Internal API load-balancer pools"
    openstack.cloud.lb_pool:
      name: "{{ item.name }}"
      lb_algorithm: "ROUND_ROBIN"
      loadbalancer: "{{ rhosp_loadbalancer_prefix }}-api-internal"
      protocol: "{{ item.protocol }}"
      state: present
    loop: "{{ rhosp_lb_private_ports }}"
    failed_when: false # there is no way of knowing if the pool already exists and it fails when creating again
    register: private_lb_pool_create_res

  - name: "Print output"
    ansible.builtin.debug:
      var: private_lb_pool_create_res

  - name: "Create Internal API load-balancer listener"
    openstack.cloud.lb_listener:
      name: "{{ item.name }}"
      load_balancer: "{{ rhosp_loadbalancer_prefix }}-api-internal"
      protocol: "{{ item.protocol }}"
      protocol_port: "{{ item.port }}"
      state: present
    loop: "{{ rhosp_lb_private_ports }}"


  - name: "Create APP load-balancer pools"
    openstack.cloud.lb_pool:
      name: "{{ item.name }}"
      lb_algorithm: "ROUND_ROBIN"
      loadbalancer: "{{ rhosp_loadbalancer_prefix }}-app"
      protocol: "{{ item.protocol }}"
      state: present
    loop: "{{ rhosp_lb_app_ports }}"
    failed_when: false # there is no way of knowing if the pool already exists and it fails when creating again
    register: app_lb_pool_create_res

  - name: "Print output"
    ansible.builtin.debug:
      var: app_lb_pool_create_res

  - name: "Create APP load-balancer listeners"
    openstack.cloud.lb_listener:
      name: "{{ item.name }}"
      load_balancer: "{{ rhosp_loadbalancer_prefix }}-app"
      protocol: "{{ item.protocol }}"
      protocol_port: "{{ item.port }}"
      state: present
    loop: "{{ rhosp_lb_app_ports }}"

  # LoadBalancer Health Monitor
  - name: "Add Health Monitors to public Load Balancer pools"
    openstack.cloud.lb_health_monitor:
      delay: 5
      # expected_codes: '200'
      health_monitor_timeout: 4
      # http_method: GET
      is_admin_state_up: true
      max_retries: 4
      max_retries_down: 3
      name: "{{ item.name }}"
      pool: "{{ item.name }}"
      state: present
      type: "TCP"
      # url_path: '/status'
    loop: "{{ rhosp_lb_api_public_ports }}"

  - name: "Add Health Monitor to Internal Load Balancer pool"
    openstack.cloud.lb_health_monitor:
      delay: 5
      # expected_codes: '200'
      health_monitor_timeout: 4
      # http_method: GET
      is_admin_state_up: true
      max_retries: 4
      max_retries_down: 3
      name: "{{ item.name }}"
      pool: "{{ item.name }}"
      state: present
      type: "TCP"
      # url_path: '/status'
    loop: "{{ rhosp_lb_api_internal_ports }}"

  - name: "Add Health Monitors to APP Load Balancer pools"
    openstack.cloud.lb_health_monitor:
      delay: 5
      # expected_codes: '200'
      health_monitor_timeout: 4
      # http_method: GET
      is_admin_state_up: true
      max_retries: 4
      max_retries_down: 3
      name: "{{ item.name }}"
      pool: "{{ item.name }}"
      state: present
      type: "TCP"
      # url_path: '/status'
    loop: "{{ rhosp_lb_app_ports }}"

  - name: "WARNING: Manually add pool to listeners"
    ansible.builtin.debug:
      msg:
      - "Pools aren't associated automatically with the Listener"
  # openstack loadbalancer listener set  --default-pool <pool> <listener>    Listener to modify (name or ID).

...
